name: SDS Viewer Workflow

on:
  push:
    branches:
      - "master"
      - "development"
  pull_request:
    branches:
      - "master"
      - "development"

jobs:
  sds_viewer_test:
    runs-on: ubuntu-22.04
    container: lironavon/docker-puppeteer-container:14.16.0
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn

      - name: Build the application (optional if required before dev)
        run: yarn build

      - name: Start development server in background
        run: |
          yarn run dev &
          npx wait-on http://localhost:3000
        env:
          CI: true

      - name: Run E2E snapshot tests
        run: npm run e2e_test
        env:
          CI: true
